# monitoring/values.yaml

replicas: 1

# A lista de apps vem vazia por padrão.
# O ArgoCD irá preenchê-la.
apps: []

# Exemplo de como a lista 'apps' deve ser preenchida no ArgoCD:
# apps:
#   - name: <nome-do-app>
#     secretName: <nome-do-secret-com-as-urls>
#     resources:
#       requests:
#         cpu: 50m
#         memory: 50Mi
