# monitoring/values.yaml

replicas: 1

apps:
  - name: app1
    secretName: heartbeat-secret-app1
    secretData:
      SERVICE_URL: "https://url-do-servico-app1.com/health"
      HEARTBEAT_URL: "https://uptime.com/ping/app1-xyz"
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

  - name: app2
    secretName: heartbeat-secret-app2
    secretData:
      SERVICE_URL: "https://url-do-servico-app2.com/status"
      HEARTBEAT_URL: "https://uptime.com/ping/app2-abc"
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

  - name: backend
    secretName: heartbeat-secret-backend-app
    secretData:
      SERVICE_URL: "https://api.backend.com/ping"
      HEARTBEAT_URL: "https://uptime.com/ping/backend-123"
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
