{{- range .Values.apps }}
{{- if .secretData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  {{- toYaml .secretData | nindent 2 }}
{{- end }}
{{- end }}
